### ISSUE TITLE
Add a docker file

### ISSUE THREAD

**Issue by yesahem** [yesahem/Medium-Blog#20]
Create a Docker File for this repo that helps user to instantly start running or testing this using Docker

**Comment by geekyharsh05** [comment]
@yesahem Can you please assign me?

**Comment by pandeyashu08** [comment]
@yesahem Can you please assign me?

**Comment by yesahem** [comment]
go ahead @pandeyashu08  but please follow the README.md file or CONTRIBUTING.md file before contribution

**Comment by pandeyashu08** [comment]
@yesahem Why do you want to containerize it, when it is running on edge. I will give you an analogy to understand this `Why do you want to drive a plane on road, when it is already capable of flying`. I have tried to implement it on my side and thereafter came across that this is a serverless backend.

**Comment by yesahem** [comment]
bro I simply want that user can run this project in as their docker file in their system. simply you have to copy all the folder in their system in docker I hope you got it !

Or if you want that I am unable to understand lets have a quick chat also @pandeyashu08

**Comment by geekyharsh05** [comment]
@yesahem Is it right to have docker for serveless hono?

**Comment by pandeyashu08** [comment]
@yesahem If you want to run your project using docker container, Hono should be in local dev environment like express

**Comment by yesahem** [comment]
I guess its okay to use any other layering tech like docker in serverless 

my reference: https://github.com/dherault/serverless-offline?tab=readme-ov-file#docker-and-layers
@pandeyashu08

**Comment by pandeyashu08** [comment]
@yesahem I tried everything possible in the best manner, I was successful in dockerizing frontend but there was an issue in backend, i was able to migrate and generate the client in the database, wrangle dev command is also working now, but the issue is it is showing that the server is started on `localhost:8787` but it does not respond. If you know how to solve this i will be happy to know about this issue. 
Here i am attaching the screenshots.

![Screenshot 2024-10-06 234607](https://github.com/user-attachments/assets/9618fd5e-27f2-4865-bd16-e54960f136d0)
![Screenshot 2024-10-06 234617](https://github.com/user-attachments/assets/719a7021-b296-4cec-975b-69e32c2e77f0)
![Screenshot 2024-10-06 234635](https://github.com/user-attachments/assets/d333e007-7ddf-4c23-a2f9-ff44e14db64f)

**Comment by yesahem** [comment]
yeah so you have to attach the port mapping to it to native localhost 8787 @pandeyashu08

**Comment by pandeyashu08** [comment]
@yesahem I did that only but it is not working.

**Comment by yesahem** [comment]
create the pr let me see it @pandeyashu08

**Comment by pandeyashu08** [comment]
@yesahem Done!

**Comment by yesahem** [comment]
Please recheck the pr commits @pandeyashu08 !!

**Comment by pandeyashu08** [comment]
@yesahem What changes do you want in the commit ??

**Comment by yesahem** [comment]
Can you please check your pr, in the commits I have mentioned what to be changed ! @pandeyashu08

**Comment by yesahem** [comment]
Please update the README.md file also for the devs using docker.. @pandeyashu08
