### ISSUE TITLE
Feature: Require Demo account

### ISSUE THREAD

**Issue by pantharshit007** [yesahem/Medium-Blog#37]
For new user its a good UX to have dummy or demo account for them to explore the website without needing to sign in unless they want to.

**Comment by pantharshit007** [comment]
/self-assign @yesahem
could you assign this to me.

**Comment by yesahem** [comment]
Go ahead @pantharshit007

**Comment by pantharshit007** [comment]
@yesahem could you check the PR

**Comment by yesahem** [comment]
> @yesahem could you check the PR

sorry but it doesn't looks good to me I have something else in my mind.....


lets simply add a clickable button called **continue without signup** 

and then if user click there then it can let user see all the posts, but whenever want to publish its fresh blog it should ask to signin or signup to the website..

**Comment by pantharshit007** [comment]
![image](https://github.com/user-attachments/assets/2bb1b04d-9a68-4518-beda-f4b07e210080)
how are we supposed to match a hashed pass with a user pass I am removing this and checking based on some other factor.

@yesahem  tip if you are merging pr then do it throughout the branches 
the guy who introduced hashing of passwords forgot to update the frontend or he never expected someone will send the hashed password to fe.

**Comment by yesahem** [comment]
Actually we don't need this feature

if you are a contributor you should have a account on vlogify, since it doesn't make sense that on a vlogging platform you have a demo account 

So closing this issue and please don't make pr for this 
Thanks for your time and efforts 


(If you want you can refer to the example that does medium have a demo account feature??)
